\set ON_ERROR_STOP on
begin;
create function pg_temp.assert_ok(v boolean,label text) returns void language plpgsql as $$ begin if v is distinct from true then raise exception 'Studio assertion: %',label;end if;end $$;
do $$
declare u1 uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();w1 uuid;w2 uuid;ep uuid;ep2 uuid;r public.review_requests;reply jsonb;request uuid:=gen_random_uuid();ch uuid;disc uuid;candidate jsonb;idea uuid;
begin
 w1:=public.studio_provision(u1,'Account one',false);w2:=public.studio_provision(u2,'Account two',false);
 perform pg_temp.assert_ok(w1<>w2,'accounts isolated');
 perform pg_temp.assert_ok(public.studio_provision(u1,'Duplicate',false)=w1,'provision idempotent');
 begin perform public.studio_assert_member(w1,u2);raise exception 'Access granted';exception when insufficient_privilege then null;end;
 candidate:='{"title":"Um assunto concreto","hook":"Um gancho verificável e concreto","angle":"Explicar um acontecimento concreto com fonte","why_now":"Um anúncio recente identificado pela fonte","limitation":"A fonte não permite inferir popularidade","source_url":"https://example.test/article","evidence_quote":"A fonte explica um acontecimento concreto"}';
 insert into public.studio_discoveries(workspace_id,profile,candidates) values(w1,'{"theme":"geek","days":7}',jsonb_build_array(candidate)) returning id into disc;
 reply:=public.studio_command(w1,u1,gen_random_uuid(),'candidate',jsonb_build_object('briefing','Uma explicação de um assunto concreto e verificável','discovery_id',disc,'candidate',candidate,'profile','{"theme":"finance"}'::jsonb));idea:=(reply->>'idea_id')::uuid;
 perform pg_temp.assert_ok((select editorial_profile->>'theme'='geek' and product_url is null and product_image_url is null and generation_requested_at is null from public.idea_queue where id=idea),'profile from stored discovery, no affiliate or generation fabricated');
 reply:=public.studio_command(w1,u1,gen_random_uuid(),'candidate',jsonb_build_object('briefing','Uma explicação de um assunto concreto e verificável','discovery_id',disc,'candidate',candidate));
 perform pg_temp.assert_ok((reply->>'idea_id')::uuid=idea,'same discovery not duplicated');
 begin perform public.studio_command(w2,u2,gen_random_uuid(),'cancel',jsonb_build_object('id',idea,'revision',0));raise exception 'Foreign idea edited';exception when insufficient_privilege then null;end;
 reply:=public.studio_command(w1,u1,gen_random_uuid(),'generate_video',jsonb_build_object('id',idea,'revision',(select revision from public.idea_queue where id=idea)));
 perform pg_temp.assert_ok(reply->>'code'='started','manual video starts while automatic production is off');
 perform pg_temp.assert_ok((select settings#>>'{pipeline,enabled}'='false' from public.studio_workspaces where id=w1),'manual action does not enable automatic consumption');
 perform pg_temp.assert_ok((select id=(reply->>'episode_id')::uuid from public.studio_next_episode()),'orchestrator advances manually started video while auto is off');
 insert into public.episodes(workspace_id)values(w1) returning id into ep;
 insert into public.episodes(workspace_id)values(w2) returning id into ep2;
 update public.episodes set status='research' where id=ep;
 update public.episodes set status='script',script_json='{"disclosures":{"contains_synthetic_media":true,"commercial_content":false}}' where id=ep;
 update public.episodes set status='assets' where id=ep;
 update public.episodes set status='rendered',render_url='https://example.test/video.mp4' where id=ep;
 update public.episodes set status='review' where id=ep;
 r:=public.studio_ensure_review(ep);
 perform pg_temp.assert_ok(r.id is not null and r.delivery_status='not_requested' and r.workspace_id=w1,'web review without Telegram');
 perform pg_temp.assert_ok((public.studio_ensure_review(ep)).id=r.id,'one current review');
 begin perform public.studio_review_action(w2,u2,request,r.id,r.fingerprint,'approve');raise exception 'Foreign review approved';exception when insufficient_privilege then null;end;
 reply:=public.studio_review_action(w1,u1,request,r.id,r.fingerprint,'approve');
 perform pg_temp.assert_ok(reply->>'code'='approved','web approval');
 perform pg_temp.assert_ok(public.studio_review_action(w1,u1,request,r.id,r.fingerprint,'approve')=reply,'review replay');
 perform pg_temp.assert_ok(not exists(select 1 from public.studio_outbox where episode_id=ep),'approve only never queues');
 perform pg_temp.assert_ok((select approval_user=u1::text and approval_fingerprint=r.fingerprint from public.episodes where id=ep),'approval bound to user/version');
 insert into public.studio_channels(workspace_id,external_id,platform,name,enabled) values(w2,'foreign','youtube','Foreign',true) returning id into ch;
 begin perform public.studio_review_action(w1,u1,gen_random_uuid(),r.id,r.fingerprint,'approve',array[ch]);raise exception 'Foreign channel approved';exception when insufficient_privilege then null;end;
 update public.episodes set script_json=script_json||'{"edited":true}' where id=ep;
 reply:=public.studio_review_action(w1,u1,gen_random_uuid(),r.id,r.fingerprint,'approve');
 perform pg_temp.assert_ok(reply->>'code'='stale','changed script cannot be approved by stale form');
 perform pg_temp.assert_ok(public.studio_reserve_usage(w1,'discovery',1),'first quota available');
 perform pg_temp.assert_ok(not public.studio_reserve_usage(w1,'discovery',1),'quota enforced');
 perform pg_temp.assert_ok(public.studio_reserve_usage(w2,'discovery',1),'other account quota independent');
 insert into public.studio_connections(workspace_id,provider,status)values(w1,'buffer','connected');
 perform pg_temp.assert_ok(public.studio_claim_refresh(w1),'first refresh claim');
 perform pg_temp.assert_ok(not public.studio_claim_refresh(w1),'single-use refresh cannot race');
 insert into public.studio_telegram_links(code_hash,workspace_id,actor,expires_at) values('one-time',w1,u1,now()+interval '10 minutes');
 perform pg_temp.assert_ok(public.studio_link_telegram('one-time','123','123'),'Telegram deep link');
 perform pg_temp.assert_ok(not public.studio_link_telegram('one-time','123','123'),'Telegram deep link single use');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u1)::text,true);
 perform set_config('studio.test_workspace',w1::text,true);
end $$;
grant usage on schema public to authenticated;
set local role authenticated;
select pg_temp.assert_ok(not exists(select 1 from public.episodes where workspace_id<>current_setting('studio.test_workspace')::uuid),'RLS episodes');
select pg_temp.assert_ok(not exists(select 1 from public.idea_queue where workspace_id<>current_setting('studio.test_workspace')::uuid),'RLS queue');
select pg_temp.assert_ok(not exists(select 1 from public.review_requests where workspace_id<>current_setting('studio.test_workspace')::uuid),'RLS reviews');
select pg_temp.assert_ok(not has_function_privilege('authenticated','public.studio_read_secret(uuid,text)','execute'),'tokens not accessible to browser');
select pg_temp.assert_ok(not has_function_privilege('authenticated','public.studio_review_action(uuid,uuid,uuid,uuid,text,text,uuid[],timestamp with time zone,text,text[])','execute'),'browser cannot assert another actor');
reset role;
rollback;
